# Generated by Django 3.2.5 on 2021-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='email',
            field=models.CharField(help_text='Enter the email address of the student', max_length=300, verbose_name='Email of Student'),
        ),
    ]
