# Generated by Django 3.2.5 on 2021-07-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usercredential_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredential',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='usercredential',
            name='crendentials_sent',
            field=models.BooleanField(default=False, verbose_name='Credentials Sent'),
        ),
    ]
