# Generated by Django 3.2.5 on 2021-07-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralCommisionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the board member', max_length=50, verbose_name='Name of Board Member')),
                ('picture', models.ImageField(help_text='Upload an image of the board member', upload_to='board-member/picture/', verbose_name='Picture of Board Member')),
            ],
        ),
    ]
