# Generated by Django 3.2.5 on 2021-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_electoralcommisionmember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoralcommisionmember',
            name='campus',
            field=models.CharField(choices=[('MC', 'Main Campus'), ('CC', 'City Campus')], default='MC', help_text='Select the campus the student is on', max_length=20, verbose_name='Campus'),
        ),
    ]
