# Generated by Django 3.2.5 on 2021-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_electoralcommisionmember_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoralcommisionmember',
            name='position_level',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Select how high in the order of power this board member is, 1 is highest', max_length=10),
        ),
    ]
