# Generated by Django 3.2.5 on 2021-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_electoralcommisionmember_position_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoralcommisionmember',
            options={'ordering': ['position_level'], 'verbose_name': 'Electoral Commission Board Member', 'verbose_name_plural': 'Electoral Commission Board Members'},
        ),
        migrations.AlterField(
            model_name='electoralcommisionmember',
            name='position_level',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5, help_text='Select how high in the order of power this board member is, 1 is highest', max_length=10),
        ),
    ]
