# Generated by Django 3.2.5 on 2021-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210723_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralcommisionmember',
            name='position_level',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5, help_text='Select how high in the order of power this board member is, 1 is highest'),
        ),
    ]
