# Generated by Django 3.2.5 on 2021-07-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the panel', max_length=255, verbose_name='Name of Panel')),
                ('enable_voting_page', models.BooleanField(help_text='Tick this button if you want people to be able to visit the voting page to vote', verbose_name='Enable Voting Page')),
                ('enable_results_page', models.BooleanField(help_text='Tick this box if you want people to be able to view the election results page', verbose_name='Enable Results Page')),
            ],
            options={
                'verbose_name': 'Page Control Panel',
                'verbose_name_plural': 'Page Control Panel',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=50, verbose_name='Full Name')),
                ('student_id', models.CharField(help_text='Enter your ID', max_length=20, verbose_name='Student ID')),
                ('email_address', models.EmailField(help_text='Enter your email address', max_length=300, null=True, verbose_name='Email Address')),
                ('message', models.TextField(help_text='Enter your message', max_length=1000, verbose_name='Complaint')),
            ],
            options={
                'verbose_name': 'Support Form',
                'verbose_name_plural': 'Support Forms',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category', max_length=50, verbose_name='Name of Category')),
                ('slug', models.SlugField(default='', help_text='Slug of the category', unique=True, verbose_name='Slug')),
                ('voters', models.ManyToManyField(related_name='voted_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter the name of the candidate', max_length=50, verbose_name='Name of Candidate')),
                ('picture', models.ImageField(help_text='Upload the image of the candidate', upload_to='candidates/pictures/', verbose_name='Picture of Candidate')),
                ('number_of_votes', models.PositiveIntegerField(default=0, verbose_name='Number of Votes')),
                ('category', models.ForeignKey(help_text='Select the category the candidate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vote_app.category')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
