# Generated by Django 3.2.5 on 2021-07-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vetting_score',
            field=models.PositiveIntegerField(default=0, help_text="Enter the score the candidate had at vetting, please don't include the percentage sign", verbose_name='Vetting Score'),
        ),
    ]
