# Generated by Django 3.2.5 on 2021-07-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_candidate_vetting_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-vetting_score'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
    ]
