# Generated by Django 3.2.5 on 2021-07-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0004_auto_20210721_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='vetting_score',
            field=models.FloatField(default=0, help_text="Enter the score the candidate had at vetting, please don't include the percentage sign", verbose_name='Vetting Score'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='yes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Number of Yeses'),
        ),
    ]
