# Generated by Django 3.2.5 on 2021-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0006_category_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
