# Generated by Django 3.2.5 on 2021-07-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0008_alter_category_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='campus',
            field=models.CharField(choices=[('MC', 'Main Campus'), ('CC', 'City Campus')], default='MC', help_text='Select the campus the student is on', max_length=20, verbose_name='Campus'),
        ),
    ]
