# Generated by Django 3.2.5 on 2021-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0009_support_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='campus',
            field=models.CharField(choices=[('MC', 'Main Campus'), ('CC', 'City Campus')], default='MC', help_text='Select your campus', max_length=20, verbose_name='Campus'),
        ),
    ]
